const PAIRS=[
['eat','fish'],['eat','meat'],['eat','pasta'],['eat','rice'],['eat','eggs'],['eat','yogurt'],['eat','vegetables'],['eat','potatoes'],['eat','salad'],['eat','fruit'],['eat','bread'],['eat','butter'],['eat','cheese'],['eat','sugar'],['eat','a sandwich'],['eat','cereal'],['eat','chocolate'],['drink','coffee'],['drink','tea'],['drink','milk'],['drink','water'],['drink','orange juice'],['have','breakfast'],['have','lunch'],['have','dinner']
];
const verbs=['eat','drink','have'];
const verbColumn=document.getElementById('verbColumn'),itemColumn=document.getElementById('itemColumn');
const scoreEl=document.getElementById('score'),comboEl=document.getElementById('combo'),timeEl=document.getElementById('time'),progressEl=document.getElementById('progressCount'),fillEl=document.getElementById('progressFill'),statusEl=document.getElementById('status');let state;
function shuffle(a){for(let i=a.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function reset(){state={score:0,combo:0,bestCombo:0,correct:0,attempts:0,time:75,done:false,selected:null};verbColumn.innerHTML='';itemColumn.innerHTML='';document.getElementById('endModal').classList.add('hidden');verbs.forEach(v=>makeCard(v,'verb'));shuffle(PAIRS.map(([,item])=>item)).forEach(item=>makeCard(item,'item'));update();clearInterval(state.timer);state.timer=setInterval(tick,1000)}
function makeCard(text,type){const b=document.createElement('button');b.type='button';b.className='match-card';b.textContent=text;b.dataset.type=type;b.dataset.word=text;b.setAttribute('aria-label',`${type}: ${text}`);b.addEventListener('click',()=>select(b));b.addEventListener('pointerdown',drag);(type==='verb'?verbColumn:itemColumn).appendChild(b)}
function select(card){if(state.done)return;if(state.selected===card){card.classList.remove('selected');state.selected=null;return}if(state.selected){if(state.selected.dataset.type!==card.dataset.type){attempt(state.selected,card);return}state.selected.classList.remove('selected')}state.selected=card;card.classList.add('selected');statusEl.textContent=`${card.textContent} selected. Tap its match.`}
function drag(e){if(state.done||e.button!==undefined&&e.button!==0)return;e.preventDefault();const card=e.currentTarget;card.setPointerCapture(e.pointerId);card.classList.add('dragging');const move=ev=>{const el=document.elementFromPoint(ev.clientX,ev.clientY);document.querySelectorAll('.match-card').forEach(x=>x.classList.toggle('target',x!==card&&x.contains(el)))};const up=ev=>{card.classList.remove('dragging');document.querySelectorAll('.target').forEach(x=>x.classList.remove('target'));document.removeEventListener('pointermove',move);document.removeEventListener('pointerup',up);const el=document.elementFromPoint(ev.clientX,ev.clientY);const target=el?.closest('.match-card');if(target&&target!==card)attempt(card,target)};document.addEventListener('pointermove',move);document.addEventListener('pointerup',up)}
function attempt(a,b){if(!a||!b||a.dataset.type===b.dataset.type||a.classList.contains('matched')||b.classList.contains('matched'))return;state.attempts++;let verb=a.dataset.type==='verb'?a.dataset.word:b.dataset.word;let item=a.dataset.type==='item'?a.dataset.word:b.dataset.word;let correct=PAIRS.some(([v,i])=>v===verb&&i===item);if(!correct){state.combo=0;a.classList.add('wrong');b.classList.add('wrong');statusEl.textContent=`Try again: ${verb} + ${item}.`;setTimeout(()=>{a.classList.remove('wrong');b.classList.remove('wrong')},400);update();return}state.correct++;state.combo++;state.bestCombo=Math.max(state.bestCombo,state.combo);state.score+=15+Math.max(0,state.combo-1)*3;a.classList.add('matched');b.classList.add('matched');a.disabled=true;b.disabled=true;state.selected=null;statusEl.textContent=`Correct! ${verb} + ${item}.`;update();if(state.correct===PAIRS.length)finish(true)}
function tick(){if(state.done)return;state.time--;update();if(state.time<=0)finish(false)}
function update(){scoreEl.textContent=state.score;comboEl.textContent=`×${state.combo}`;timeEl.textContent=`${String(Math.floor(state.time/60)).padStart(2,'0')}:${String(state.time%60).padStart(2,'0')}`;progressEl.textContent=state.correct;fillEl.style.width=`${state.correct/PAIRS.length*100}%`}
function finish(won){state.done=true;clearInterval(state.timer);document.getElementById('finalScore').textContent=state.score;document.getElementById('accuracy').textContent=`${state.attempts?Math.round(state.correct/state.attempts*100):0}%`;document.getElementById('bestCombo').textContent=`×${state.bestCombo}`;document.getElementById('endTitle').textContent=won?'Excellent!':'Time’s up!';document.getElementById('endMessage').textContent=won?'You matched all 25 combinations.':'Play again and try to beat your score.';document.getElementById('resultIcon').textContent=won?'🏆':'⏱️';document.getElementById('endModal').classList.remove('hidden')}
document.getElementById('playAgain').addEventListener('click',reset);reset();
