const ITEMS=[
['fish','food'],['meat','food'],['pasta','food'],['rice','food'],['eggs','food'],['yogurt','food'],['vegetables','food'],['potatoes','food'],['salad','food'],['fruit','food'],['bread','food'],['butter','food'],['cheese','food'],['sugar','food'],['a sandwich','food'],['cereal','food'],['chocolate','food'],['coffee','drinks'],['tea','drinks'],['milk','drinks'],['water','drinks'],['orange juice','drinks']
];
const tray=document.getElementById('cardTray'),foodItems=document.getElementById('foodItems'),drinkItems=document.getElementById('drinkItems');
const scoreEl=document.getElementById('score'),comboEl=document.getElementById('combo'),timeEl=document.getElementById('time'),progressEl=document.getElementById('progressCount'),fillEl=document.getElementById('progressFill'),statusEl=document.getElementById('status');
let state;
function shuffle(a){for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function reset(){state={score:0,combo:0,bestCombo:0,correct:0,attempts:0,time:90,done:false,selected:null};foodItems.innerHTML='';drinkItems.innerHTML='';tray.innerHTML='';document.getElementById('endModal').classList.add('hidden');shuffle([...ITEMS]).forEach(([word,category],i)=>makeCard(word,category,i));update();clearInterval(state.timer);state.timer=setInterval(tick,1000)}
function makeCard(word,category,index){const card=document.createElement('button');card.type='button';card.className='word-card';card.textContent=word;card.dataset.category=category;card.dataset.word=word;card.dataset.index=index;card.setAttribute('aria-label',`Vocabulary word: ${word}. Drag or tap to place.`);card.addEventListener('pointerdown',startPointer);card.addEventListener('click',()=>selectCard(card));tray.appendChild(card)}
function selectCard(card){if(state.done)return;if(state.selected===card){card.classList.remove('selected');state.selected=null;return}tray.querySelectorAll('.selected').forEach(x=>x.classList.remove('selected'));state.selected=card;card.classList.add('selected');statusEl.textContent=`${card.textContent} selected. Tap Food or Drinks.`}
function startPointer(e){if(state.done||e.button!==undefined&&e.button!==0)return;e.preventDefault();const card=e.currentTarget;card.setPointerCapture(e.pointerId);card.classList.add('dragging');const move=ev=>{const el=document.elementFromPoint(ev.clientX,ev.clientY);document.querySelectorAll('.drop-zone').forEach(z=>z.classList.toggle('drag-over',z.contains(el)))};const up=ev=>{card.classList.remove('dragging');document.querySelectorAll('.drop-zone').forEach(z=>z.classList.remove('drag-over'));card.releasePointerCapture?.(e.pointerId);document.removeEventListener('pointermove',move);document.removeEventListener('pointerup',up);const el=document.elementFromPoint(ev.clientX,ev.clientY);const zone=el?.closest('.drop-zone');if(zone)place(card,zone.dataset.category);};document.addEventListener('pointermove',move);document.addEventListener('pointerup',up)}
document.querySelectorAll('.drop-zone').forEach(zone=>{zone.addEventListener('click',()=>{if(state.selected){place(state.selected,zone.dataset.category)}});zone.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&state.selected){e.preventDefault();place(state.selected,zone.dataset.category)}})});
function place(card,category){if(!card||state.done)return;state.attempts++;const expected=card.dataset.category;if(expected!==category){state.combo=0;card.classList.remove('wrong');void card.offsetWidth;card.classList.add('wrong');statusEl.textContent=`Not quite. ${card.textContent} is not ${category}.`;comboEl.textContent='×0';setTimeout(()=>card.classList.remove('wrong'),400);return}state.correct++;state.combo++;state.bestCombo=Math.max(state.bestCombo,state.combo);state.score+=10+Math.max(0,state.combo-1)*2;const target=category==='food'?foodItems:drinkItems;const pill=document.createElement('span');pill.className='placed-item correct';pill.textContent=card.textContent;target.appendChild(pill);card.remove();state.selected=null;statusEl.textContent=`Correct! ${pill.textContent} goes in ${category}.`;update();if(state.correct===ITEMS.length)finish(true)}
function tick(){if(state.done)return;state.time--;update();if(state.time<=0)finish(false)}
function update(){scoreEl.textContent=state.score;comboEl.textContent=`×${state.combo}`;timeEl.textContent=`${String(Math.floor(state.time/60)).padStart(2,'0')}:${String(state.time%60).padStart(2,'0')}`;progressEl.textContent=state.correct;fillEl.style.width=`${state.correct/ITEMS.length*100}%`}
function finish(won){state.done=true;clearInterval(state.timer);document.getElementById('finalScore').textContent=state.score;document.getElementById('accuracy').textContent=`${state.attempts?Math.round(state.correct/state.attempts*100):0}%`;document.getElementById('bestCombo').textContent=`×${state.bestCombo}`;document.getElementById('endTitle').textContent=won?'Excellent!':'Time’s up!';document.getElementById('endMessage').textContent=won?'You sorted all 22 words correctly.':'You can try again and beat your score.';document.getElementById('resultIcon').textContent=won?'🏆':'⏱️';document.getElementById('endModal').classList.remove('hidden')}
document.getElementById('playAgain').addEventListener('click',reset);reset();
