/* Multiple Choice Quiz — Units 1–12. 40 questions per unit. */
const QUIZ_UNITS = {
  1: [

    // --- Grammar ---
    { q: "Where ________ from?", options: ["is he","is","he is"], answer: 0 },
    { q: "Hello, ________ Maria.", options: ["I'm","I","am"], answer: 0 },
    { q: "A: Is she a good student?  B: ________.", options: ["Yes, is","Yes, she is","Yes, is she"], answer: 1 },
    { q: "A: Are you from Italy?  B: ________.", options: ["No, I not","No, am I not","No, I'm not"], answer: 2 },
    { q: "What's ________ name?", options: ["you","you're","your"], answer: 2 },
    { q: "________ Amanda from the United States?", options: ["Am","Are","Is"], answer: 2 },
    { q: "Tom ________ from France.", options: ["not","aren't","isn't"], answer: 2 },
    { q: "Are ________ Yumiko?", options: ["he","you","she"], answer: 1 },
    { q: "Where ________ from?", options: ["you","you are","are you"], answer: 2 },
    { q: "Rio de Janeiro ________ in Brazil.", options: ["it's","is","are"], answer: 1 },
    { q: "Where is ________?", options: ["I","he","you"], answer: 1 },
    { q: "A: Is it from Spain?  B: No, ________.", options: ["it is","it not","it isn't"], answer: 2 },
    { q: "________ you from England?", options: ["Am","Are","Is"], answer: 1 },
    { q: "________ in room 7.", options: ["You are no","You not","You aren't"], answer: 2 },
    { q: "________ from China.", options: ["Is","She","She is"], answer: 2 },
    { q: "I ________ in room 12.", options: ["isn't","'m not","aren't"], answer: 1 },
    { q: "________ Melanie.", options: ["I'm not","Am not","I not"], answer: 0 },
    { q: "Mo ________ Egypt.", options: ["from","is","is from"], answer: 2 },
    { q: "Where ________?", options: ["it is","are you","I am"], answer: 1 },
    { q: "________ Carlos?", options: ["He is","Is he","Is"], answer: 1 },
    // --- Vocabulary: complete the sentence ---
    { q: "Today is ________.", options: ["Monday","monday","afternoon"], answer: 0 },
    { q: "Is Gilberto from ________?", options: ["brazil","Brazil","brazils"], answer: 1 },
    { q: "I'm not ________.", options: ["from Mexico","from mexico","of Mexico"], answer: 0 },
    { q: "She's from ________.", options: ["the France","france","France"], answer: 2 },
    { q: "My birthday is on ________.", options: ["afternoon","three","Friday"], answer: 2 },
    // --- Vocabulary: what comes next ---
    { q: "one, two, three, ________", options: ["five","four","six"], answer: 1 },
    { q: "Friday, Saturday, Sunday, ________", options: ["Tuesday","Monday","Wednesday"], answer: 1 },
    { q: "five, six, seven, ________", options: ["eight","eigth","eithg"], answer: 0 },
    { q: "one, three, six, ________", options: ["nine","seven","eight"], answer: 0 },
    { q: "Monday, Tuesday, Wednesday, ________", options: ["Thurday","thursday","Thursday"], answer: 2 },
    // --- Vocabulary: everyday phrases ---
    { q: "Can you repeat that, ________?", options: ["thank you","please","sorry"], answer: 1 },
    { q: "I'm sorry, I don't ________!", options: ["nice","repeat","understand"], answer: 2 },
    { q: "How can I ________ you?", options: ["help","nice","sorry"], answer: 0 },
    { q: "How do you ________ your name?", options: ["meet","repeat","spell"], answer: 2 },
    { q: "A: Hi Sara!  B: ________ Ana.", options: ["Hello","Nice","Good"], answer: 0 },
    { q: "Open your ________, please.", options: ["boards","books","pages"], answer: 1 },
    { q: "A: Bye, Emilio.  B: Bye. ________ you tomorrow!", options: ["Look","See","Are"], answer: 1 },
    { q: "A: Bye!  B: ________!", options: ["Sorry","Hello","Goodbye"], answer: 2 },
    { q: "________ I'm late.", options: ["Sorry","Hello","Thanks"], answer: 0 },
    { q: "Hello. Nice to ________ you.", options: ["meet","repeat","spell"], answer: 0 },
  ],
  2: [

    // --- Grammar ---
    { q: "A: How are you?  B: I'm ________, thanks.", options: ["fine","19","Brazilian"], answer: 0 },
    { q: "A: ________ are they?  B: They're 18.", options: ["How","How old","Old how"], answer: 1 },
    { q: "They're from Italy. They ________ German.", options: ["aren't","isn't","not"], answer: 0 },
    { q: "A: ________ the next class?  B: It's tomorrow at 10.00.", options: ["Where's","What's","When's"], answer: 2 },
    { q: "A: ________ Miguel?  B: He's a friend from school.", options: ["Who is","How is","Who are"], answer: 0 },
    { q: "A: ________ your email?  B: It's matt35@themail.com.", options: ["Where's","What's","Who's"], answer: 1 },
    { q: "A: Are Tom and Tim brothers?  B: Yes, ________.", options: ["are they","they aren't","they are"], answer: 2 },
    { q: "Where are they ________?", options: ["for","good","from"], answer: 2 },
    { q: "________ they in my class?", options: ["Is","Are","Am"], answer: 1 },
    { q: "A: When's your birthday?  B: ________ Tuesday.", options: ["It's on","On it","It's to"], answer: 0 },
    { q: "________ Chinese. We're from Japan.", options: ["They not","You're not","We're not"], answer: 2 },
    { q: "________ your friend's name?", options: ["When's","Who's","What's"], answer: 2 },
    { q: "A: ________ phone number?  B: It's 423-618-2057.", options: ["What you","What","What's your"], answer: 2 },
    { q: "________ Egyptian. They are from Cairo.", options: ["They","There","They're"], answer: 2 },
    { q: "________ here on business.", options: ["We're","Are we","We"], answer: 0 },
    { q: "________ I late?", options: ["Is","Am","Are"], answer: 1 },
    { q: "A: ________ the number after eleven?  B: It's twelve.", options: ["When's","Where's","What's"], answer: 2 },
    { q: "They ________ class number two.", options: ["are in","is in","in are"], answer: 0 },
    { q: "A: ________ they?  B: They are students from Turkey.", options: ["Where are","How are","Who are"], answer: 2 },
    { q: "________ late?", options: ["Are we","Am we","Is we"], answer: 0 },

    // --- Vocabulary: picture questions ---
    { q: "What is it?", options: ["a chair","a table","a window"], answer: 0, image: "chair" },
    { q: "What is it?", options: ["a board","a coat","a pen"], answer: 1, image: "coat" },
    { q: "What is it?", options: ["a laptop","a table","a book"], answer: 0, image: "laptop" },
    { q: "What is it?", options: ["a laptop","a door","a window"], answer: 1, image: "door" },
    { q: "What is it?", options: ["a laptop","a door","a window"], answer: 2, image: "window" },
    { q: "What is it?", options: ["a dictionary","a piece of paper","a book"], answer: 1, image: "paper" },
    { q: "What is it?", options: ["a window","a door","a board"], answer: 2, image: "board" },
    { q: "What is it?", options: ["a dictionary","a book","a piece of paper"], answer: 1, image: "book" },

    // --- Vocabulary: complete the sentence ---
    { q: "They are ________.", options: ["China","chinese","Chinese"], answer: 2 },
    { q: "________ your address?", options: ["Where's","How's","What's"], answer: 2 },
    { q: "The class is on ________.", options: ["Friday","morning","15"], answer: 0 },
    { q: "How ________ are you?", options: ["from","old","name"], answer: 1 },
    { q: "Open your ________ to page 45.", options: ["doors","laptops","books"], answer: 2 },
    { q: "________ are Swiss.", options: ["They","He","She"], answer: 0 },
    { q: "________ morning.", options: ["Sorry","Excuse","Good"], answer: 2 },
    { q: "What's your ________ number?", options: ["address","name","phone"], answer: 2 },
    { q: "Yes. I'm ________.", options: ["British","England","the UK"], answer: 0 },
    { q: "I'm Emily Parr. I ________ a reservation.", options: ["not","have","am"], answer: 1 },
    { q: "Excuse me. How do you ________ your surname?", options: ["spell","are","see"], answer: 0 },
    { q: "A: Can you ________ that, please?  B: Yes. It's 0905644381.", options: ["see","repeat","spell"], answer: 1 },
  ],
  3: [

    // --- Grammar ---
    { q: "What is ________?", options: ["this", "those", "these"], answer: 0 },
    { q: "Open ________ windows, please.", options: ["a", "an", "the"], answer: 2 },
    { q: "A: What are those?  B: They’re ________.", options: ["dictionary", "dictionaries", "dictionarys"], answer: 1 },
    { q: "It’s ________ ID card.", options: ["a", "an", "two"], answer: 1 },
    { q: "Those are ________.", options: ["T-shirt", "a T-shirt", "T-shirts"], answer: 2 },
    { q: "________ a pen.", options: ["These are", "It’s", "This are"], answer: 1 },
    { q: "I have two ________ in my bag.", options: ["keyes", "key", "keys"], answer: 2 },
    { q: "How much are these ________?", options: ["watchs", "watches", "watch"], answer: 1 },
    { q: "A: What is that?  B: It’s ________ purse.", options: ["a", "an", "the"], answer: 0 },
    { q: "Those ________ nice sunglasses.", options: ["is", "am", "are"], answer: 2 },
    { q: "Who are ________ boys over there?", options: ["that", "these", "those"], answer: 2 },
    { q: "________ in your bag?", options: ["Who’s", "What’s", "How’s"], answer: 1 },
    { q: "A: What are those?  B: They are ________.", options: ["credit card", "credits cards", "credit cards"], answer: 2 },
    { q: "My English ________ are on Mondays and Tuesdays.", options: ["class", "classes", "classies"], answer: 1 },
    { q: "________ those?", options: ["What’s", "What’re", "What are"], answer: 2 },
    { q: "How much are these ________?", options: ["muges", "mug", "mugs"], answer: 2 },
    { q: "________ is my coffee.", options: ["This", "These", "The"], answer: 0 },
    { q: "A: Are ________ your books over there?  B: No. These are my books.", options: ["this", "these", "those"], answer: 2 },
    { q: "________ is your phone charger.", options: ["Here", "What", "These"], answer: 0 },
    { q: "You’re in room 31. This is ________ key.", options: ["there", "these", "the"], answer: 2 },

    // --- Vocabulary: picture questions ---
    { q: "What is it?", options: ["a bag", "a mug", "a coat"], answer: 0, image: "bag" },
    { q: "What are they?", options: ["pens", "glasses", "keys"], answer: 1, image: "glasses" },
    { q: "What is it?", options: ["a laptop", "a mobile phone", "a wallet"], answer: 1, image: "mobile-phone" },
    { q: "What is it?", options: ["a camera", "a watch", "a laptop"], answer: 0, image: "camera" },
    { q: "What is it?", options: ["a camera", "a photo", "a credit card"], answer: 1, image: "photo" },
    { q: "What is it?", options: ["a passport", "a photo", "a credit card"], answer: 0, image: "passport" },
    { q: "What is it?", options: ["a watch", "a notebook", "a T-shirt"], answer: 0, image: "watch" },
    { q: "What is it?", options: ["a purse", "a photo", "a credit card"], answer: 2, image: "credit-card" },
    { q: "What are they?", options: ["glasses", "umbrellas", "key rings"], answer: 2, image: "key-rings" },
    { q: "What is it?", options: ["a wallet", "a credit card", "a bag"], answer: 0, image: "wallet" },

    // --- Vocabulary: complete the sentence ---
    { q: "Are these your ________?", options: ["T-shirt", "cap", "glasses"], answer: 2 },
    { q: "________ a nice teddy.", options: ["That’s", "These", "They’re"], answer: 0 },
    { q: "A: How much is that?  B: It’s ________.", options: ["£6.99", "Saturday", "those"], answer: 0 },
    { q: "That’s a nice football ________.", options: ["caps", "scarf", "shirts"], answer: 1 },
    { q: "There are three ________ here.", options: ["passport", "passeports", "passports"], answer: 2 },
    { q: "_______ your change.", options: ["Here’s", "How’s", "Wait"], answer: 0 },
    { q: "That’s twenty pounds, ________.", options: ["please", "much", "these"], answer: 0 },
    { q: "Look at ________. It’s great!", options: ["those", "these", "this"], answer: 2 },
    { q: "A ________ much is that mug?", options: ["How", "That", "What"], answer: 0 },
    { q: "A: Ice ________ lemon?  B: No, thanks.", options: ["an", "and", "that"], answer: 1 },
  ],
  4: [

{q:"What's ________ name?",options:["her","your","their"],answer:1},{q:"Where are ________ bags?",options:["our","ours","we"],answer:0},{q:"Six hundred pounds? That ________.",options:["an expensive camera is","is a camera expensive","is an expensive camera"],answer:2},{q:"Is that ________ car?",options:["Carlos","Carloses","Carlos'"],answer:2},{q:"No. ________ friends aren't here today.",options:["Her","Their","Our"],answer:1},{q:"Yes. ________ husband is over there.",options:["Our","Your","My"],answer:2},{q:"These books are very ________.",options:["old","fast","slow"],answer:0},{q:"This is our ________ house.",options:["parents","parent's","parents'"],answer:2},{q:"Chantelle and Veronique are French. ________ husbands are Italian.",options:["Their","They","Her"],answer:0},{q:"Here are ________ sandwiches: one cheese, and one tuna.",options:["your","yours","your's"],answer:0},{q:"This is my new book. ________ very good.",options:["It","It's","Its"],answer:1},{q:"Alina is ________ sister.",options:["Brunos","Bruno","Bruno's"],answer:2},{q:"________ mother and father aren't from England.",options:["Their","They","There"],answer:0},{q:"This is my ________, Sara. She's a doctor.",options:["brother wife","brother's wife","wife's brother"],answer:1},{q:"This is ________ mother. My father isn't here.",options:["her","his","my"],answer:2},{q:"My father's name is Tom. ________ sister's name is Erica.",options:["His","Their","Her"],answer:0},{q:"Those are ________.",options:["cars fast","fast cars","fasts cars"],answer:1},{q:"It's a ________ car.",options:["cheap","Hiro's","our"],answer:0},{q:"Her ________ are nice.",options:["son","sons","son's"],answer:1},{q:"That's Marek's girlfriend. ________ beautiful.",options:["Her's","She's","She"],answer:1},
    // --- Vocabulary: additional words and phrases ---
    { q: "My father is married to my ________.", options: ["mother", "wife", "daughter"], answer: 0 },
    { q: "My ________ is very nice. His name is Angelo.", options: ["boyfriend", "girlfriend", "woman"], answer: 0 },
    { q: "Patricia is my ________.", options: ["children", "sister", "friends"], answer: 1 },
    { q: "That's my ________. He is 15 today.", options: ["children", "daughter", "son"], answer: 2 },
    { q: "My brother's married. His ________ name is Carmen.", options: ["wife's", "husband's", "sister's"], answer: 0 },
    { q: "These are my ________. Their names are Ashley and Miguel.", options: ["man", "people", "friends"], answer: 2 },
    { q: "Sally is 21. Her ________ are 55.", options: ["father", "mother", "mother and father"], answer: 2 },
    { q: "My friend has a very ________ name.", options: ["cheap", "fast", "long"], answer: 2 },
    { q: "That coat is very ________.", options: ["difficult", "dirty", "slow"], answer: 1 },
    { q: "That car is \u00a3500. Wow! That's ________!", options: ["big", "cheap", "long"], answer: 1 },
    { q: "Your house is very ________.", options: ["clean", "fast", "short"], answer: 0 },
    { q: "These sunglasses are very ________. They're \u00a3150.", options: ["easy", "expensive", "long"], answer: 1 },
    { q: "That's an ________ bag. It's a nice colour. It's \u00a3250.", options: ["expensive", "big", "ugly"], answer: 0 },
    { q: "The opposite of short is ________.", options: ["long", "old", "cheap"], answer: 0 },
    { q: "The opposite of clean is ________.", options: ["dirty", "fast", "easy"], answer: 0 },
    { q: "The opposite of cheap is ________.", options: ["expensive", "short", "old"], answer: 0 },
    { q: "A male child is a ________.", options: ["son", "daughter", "wife"], answer: 0 },
    { q: "A female child is a ________.", options: ["husband", "daughter", "boyfriend"], answer: 1 },
    { q: "People who know each other well can be ________.", options: ["friends", "cars", "houses"], answer: 0 },
    { q: "If something costs a lot of money, it is ________.", options: ["cheap", "expensive", "easy"], answer: 1 },
  ],
  5: [

{q:"Do you drink coffee in the morning? Yes, ________.",options:["do I","I am","I do"],answer:2},{q:"We ________ TV in the morning.",options:["don't watch","are watch","not watch"],answer:0},{q:"________ you live here?",options:["Are","Do","Have"],answer:1},{q:"Marco and Giulia ________ Italian.",options:["speak","speaks","is speak"],answer:0},{q:"I ________ newspapers.",options:["don't read","read not","'m not read"],answer:0},{q:"I ________ chocolate.",options:["like","likes","are like"],answer:0},{q:"Do people in Germany have a big breakfast? No, they ________.",options:["not","don't","do"],answer:1},{q:"________ work at weekends?",options:["Do","Do you","You"],answer:1},{q:"We ________ beer.",options:["don't drink","not drink","don't drinks"],answer:0},{q:"They ________ to the radio in the morning.",options:["are listen","listen","listens"],answer:1},{q:"Do you study English? Yes, we _______.",options:["are","do","is"],answer:1},{q:"They ________ three children.",options:["has","have","haves"],answer:1},{q:"Javier and Ellie ________ business at university.",options:["study","studies","studys"],answer:0},{q:"We don't ________ a dog.",options:["has","have","likes"],answer:1},{q:"I ________ in a bank.",options:["is work","works","work"],answer:2},{q:"Do you ________ a sandwich? Yes, please.",options:["eats","want","wants"],answer:1},{q:"I ________ cereal for breakfast.",options:["no eat","not eat","don't eat"],answer:2},{q:"Do you have a mobile phone? No, I _______.",options:["don't","do","not"],answer:0},{q:"________ tea?",options:["They drink","Are they drink","Do they drink"],answer:2},{q:"Do you live at home? Yes, I ________.",options:["live","am","do"],answer:2},
    // --- Vocabulary: additional words and phrases ---
    { q: "Which word is different from 'tea'?", options: ["coffee", "salad", "milk"], answer: 1 },
    { q: "Which word is different from 'afternoon'?", options: ["evening", "morning", "dinner"], answer: 2 },
    { q: "Which word is different from 'cereal'?", options: ["pasta", "flat", "bread"], answer: 1 },
    { q: "Which word is different from 'six'?", options: ["ten", "fifteen", "afternoon"], answer: 2 },
    { q: "Which word is different from 'read'?", options: ["watch", "listen", "sandwich"], answer: 2 },
    { q: "Which word is different from 'speak'?", options: ["milk", "study", "work"], answer: 0 },
    { q: "Which word is different from 'eggs'?", options: ["water", "rice", "fruit"], answer: 0 },
    { q: "Which word is different from 'dinner'?", options: ["breakfast", "lunch", "eggs"], answer: 2 },
    { q: "Which word is different from 'drink'?", options: ["eat", "live", "don't"], answer: 2 },
    { q: "Which word is different from 'newspaper'?", options: ["watch", "radio", "TV"], answer: 0 },
    { q: "It's a ________ to nine.", options: ["half", "o'clock", "quarter"], answer: 2 },
    { q: "For breakfast, I drink ________ or milk.", options: ["cereal", "cheese", "juice"], answer: 2 },
    { q: "Are you ________? Do you want a drink?", options: ["hungry", "thirsty", "tired"], answer: 1 },
    { q: "It's half ________ eight.", options: ["past", "o'clock", "to"], answer: 0 },
    { q: "I want ________ in my sandwich, please.", options: ["cheese", "rice", "juice"], answer: 0 },
    { q: "Do you ________ the newspaper in the morning?", options: ["read", "go", "watch"], answer: 0 },
    { q: "I'm ________. It's time for bed.", options: ["hot", "hungry", "tired"], answer: 2 },
    { q: "Do they ________ TV?", options: ["listen", "watch", "read"], answer: 1 },
    { q: "I don't ________ meat. I don't like it.", options: ["eat", "drink", "go to"], answer: 0 },
    { q: "We don't ________ long flights.", options: ["like", "live", "work"], answer: 0 },
  ],
  6: [

{q:"Does Maria live in a flat? No, she ________.",options:["not","don't","doesn't"],answer:2},{q:"I ________ drink tea.",options:["don't never","never","not"],answer:1},{q:"What ________ do you go to bed?",options:["time","is time","is the time"],answer:0},{q:"________ Rita live?",options:["Where does","Where is","Where do"],answer:0},{q:"Huang ________ work in an office.",options:["don't usually","doesn't usually","usually"],answer:1},{q:"________ coffee?",options:["Does he drinks","Is he drink","Does he drink"],answer:2},{q:"My father ________ newspapers.",options:["don't read","reads not","doesn't read"],answer:2},{q:"Do you work in a factory? Yes, ________.",options:["do I","I am","I do"],answer:2},{q:"My sister ________ TV in the evening.",options:["watch","watchs","watches"],answer:2},{q:"Ravi ________ eats eggs for breakfast.",options:["sometime","sometimes","some"],answer:1},{q:"Does Olivia speak Turkish? ________.",options:["Yes, she do","No, she don't","No, she doesn't"],answer:2},{q:"She ________ lunch in restaurants.",options:["eats never","never eat","never eats"],answer:2},{q:"My brother ________ French and German at university.",options:["study","studys","studies"],answer:2},{q:"He's a waiter. He ________ his job.",options:["like","likes","don't like"],answer:1},{q:"What ________ your daughter eat for breakfast?",options:["do","does","is"],answer:1},{q:"Marcia ________ at a quarter to seven.",options:["gets up always","always gets up","gets always up"],answer:1},{q:"Does your brother ________ to the gym on the weekends?",options:["go","goes","go's"],answer:0},{q:"________ you listen to the radio sometimes?",options:["Do","Does","Are"],answer:0},{q:"Chris and his wife ________ two children.",options:["have","has","does"],answer:0},{q:"Does your brother live at home? Yes, he ________.",options:["live","lives","does"],answer:2},
    // --- Vocabulary: additional words and phrases ---
    { q: "Which word is different from 'journalist'?", options: ["factory worker", "school", "shop assistant"], answer: 1 },
    { q: "Which word is different from 'lunch'?", options: ["breakfast", "housework", "dinner"], answer: 1 },
    { q: "Which word is different from 'factory'?", options: ["waiter", "home", "restaurant"], answer: 1 },
    { q: "Which word is different from 'in the street'?", options: ["in a restaurant", "in an office", "go shopping"], answer: 2 },
    { q: "Which word is different from 'teacher'?", options: ["receptionist", "taxi driver", "factory"], answer: 2 },
    { q: "Which word is different from 'always'?", options: ["sometimes", "never", "finish"], answer: 2 },
    { q: "Ketlin always has ________ at work.", options: ["breakfast", "office", "gym"], answer: 0 },
    { q: "Amany's a ________. She works in a school.", options: ["waitress", "teacher", "policewoman"], answer: 1 },
    { q: "Margarida is a receptionist in ________.", options: ["a shop", "the street", "an office"], answer: 2 },
    { q: "I ________ work at five o'clock.", options: ["do", "finish", "time"], answer: 1 },
    { q: "Samuel works in a ________.", options: ["bank", "office", "waiter"], answer: 0 },
    { q: "Theo works as a ________ assistant.", options: ["factory", "shop", "taxi"], answer: 1 },
    { q: "What time do you usually ________?", options: ["go homework", "do homework", "make homework"], answer: 1 },
    { q: "Where do you ________?", options: ["home", "work", "bed"], answer: 1 },
    { q: "Does he sometimes ________ a big lunch?", options: ["do", "go", "have"], answer: 2 },
    { q: "In the morning, do you have a ________?", options: ["TV", "breakfast", "shower"], answer: 1 },
    { q: "Does Mika usually have a ________ in the afternoon?", options: ["lunch", "coffee", "work"], answer: 1 },
    { q: "Do you ________ the gym at the weekend?", options: ["do", "go to", "make"], answer: 1 },
    { q: "Do you always make ________ in the evening?", options: ["dinner", "housework", "a shower"], answer: 1 },
    { q: "Does Marco always have pasta ________?", options: ["for lunch", "at work", "in the gym"], answer: 0 },
  ],
  7: [

{q:"________ does your brother start university?",options:["What","Who","When"],answer:2},{q:"Ask ________. She knows the answer!",options:["her","it","him"],answer:0},{q:"________ do you live now?",options:["When","Why","Where"],answer:2},{q:"________ you late?",options:["Do","Why","Why are"],answer:2},{q:"________ down, please. I want to talk to you.",options:["Sit","Sitting","To sit"],answer:0},{q:"________ kind of films do you like?",options:["How","What","Who"],answer:1},{q:"How old ________ your girlfriend?",options:["is","are","does"],answer:0},{q:"________ you meet your friends on Saturdays?",options:["Are","Is","Do"],answer:2},{q:"Who do you usually have dinner with? My children.",options:["How","Who","When"],answer:1},{q:"________ live in Mexico City.",options:["They're","Us","We"],answer:2},{q:"________ do you usually go to the gym?",options:["Are","What time","Who"],answer:1},{q:"________ talk.",options:["Aren't","Don't","Not"],answer:1},{q:"My neighbours are not very nice. I don't like ________.",options:["they","him","them"],answer:2},{q:"________ the shop near here?",options:["Are","Is","Where"],answer:1},{q:"I don't like ________.",options:["us","it","we"],answer:1},{q:"________ to work by car each day?",options:["How do you travel","Are you travel","Do you travel"],answer:0},{q:"________ here!",options:["Come","Do","Don't"],answer:0},{q:"________ your friend's name?",options:["How spell you","How you do spell","How do you spell"],answer:2},{q:"What time ________?",options:["it is now","is it now","now it is"],answer:1},{q:"Please, listen to ________.",options:["I","she","me"],answer:2},
    // --- Vocabulary: additional words and phrases ---
    { q: "We ________ films on Friday nights.", options: ["do", "go out", "watch"], answer: 2 },
    { q: "What's the ________ today?", options: ["date", "birthday", "month"], answer: 0 },
    { q: "I ________ Jennifer Lawrence is great!", options: ["like", "think", "prefer"], answer: 1 },
    { q: "Are you ________ it's the sixth today?", options: ["definitely", "sure", "think"], answer: 1 },
    { q: "Do you ________ sport at the weekend?", options: ["do", "go", "make"], answer: 0 },
    { q: "It's the ________ of April.", options: ["five", "fifth", "fifteen"], answer: 1 },
    { q: "My mother's ________ is on 20th June.", options: ["birthday", "birthdate", "month"], answer: 0 },
    { q: "I don't like science fiction films. I ________ dramas.", options: ["likes", "act", "prefer"], answer: 2 },
    { q: "They always go ________ on Saturday.", options: ["out", "swim", "travel"], answer: 0 },
    { q: "We leave on the ________ of August.", options: ["nine", "nineteen", "ninth"], answer: 2 },
    { q: "Go out goes with ________.", options: ["at night", "home", "theatre"], answer: 0 },
    { q: "Stay goes with ________.", options: ["to the beach", "at home", "friends"], answer: 1 },
    { q: "Do goes with ________.", options: ["swimming", "sport", "tennis"], answer: 1 },
    { q: "Go goes with ________.", options: ["in the mountains", "to the cinema", "walk"], answer: 1 },
    { q: "Make goes with ________.", options: ["home", "relax", "breakfast"], answer: 2 },
    { q: "Beatriz ________ the piano every day.", options: ["does", "sits", "plays"], answer: 2 },
    { q: "How do you ________ at the weekend?", options: ["stay", "meet", "relax"], answer: 2 },
    { q: "Do you want to go ________ for dinner?", options: ["out", "with", "in"], answer: 0 },
    { q: "In my ________ time, I always read books.", options: ["free", "date", "birthday"], answer: 0 },
    { q: "My favourite kind of film is a ________.", options: ["drama", "restaurant", "piano"], answer: 0 },
  ],
  8: [

{q:"Where ________ I park my car?",options:["can","is","can't"],answer:0},{q:"Stephan loves ________ at the weekend.",options:["cycle","cycling","cycleing"],answer:1},{q:"Can I use my mobile phone here? No, ________. I'm sorry.",options:["you can't use","you can't","you don't"],answer:1},{q:"Marta doesn't like ________ TV.",options:["watches","watching","watch"],answer:1},{q:"My brother doesn't like ________ out.",options:["go eat","eat","eating"],answer:2},{q:"You ________ football in the park.",options:["can't play","can't to play","can't playing"],answer:0},{q:"Do you ________?",options:["driving like","like drive","like driving"],answer:2},{q:"I'm sorry. You ________ take photos here.",options:["can't","don't can","can't to"],answer:0},{q:"Do you like ________?",options:["shop","shoping","shopping"],answer:2},{q:"At work, I ________ at 3.30 on Fridays.",options:["can home go","go home can","can go home"],answer:2},{q:"What music do you like ________?",options:["to listen","listening","listening to"],answer:2},{q:"________ buy a Spanish newspaper in this shop?",options:["Can I","I can","Can I to"],answer:0},{q:"My mother ________ flying.",options:["can't like","don't like","doesn't like"],answer:2},{q:"They ________ doing housework.",options:["hating","to hate","hate"],answer:2},{q:"Do you like ________?",options:["swim","swiming","swimming"],answer:2},{q:"Can ________ with me?",options:["come my friend","my friend come","my friend to come"],answer:1},{q:"What ________ at the weekend?",options:["do they like do","like they doing","do they like doing"],answer:2},{q:"You ________ nice vegetables here.",options:["can't to buy","can buy","can buying"],answer:1},{q:"Do you like camping? Yes, I ________ it.",options:["hate","don't like","love"],answer:2},{q:"My father hates ________ in the city.",options:["drive","driving","driveing"],answer:1},
    // --- Vocabulary: additional words and phrases ---
    { q: "David hates ________ TV series.", options: ["watching", "going", "having"], answer: 0 },
    { q: "Yes, you can ________ by credit card.", options: ["do", "pay", "use"], answer: 1 },
    { q: "My sister loves ________ shoes.", options: ["buying", "shopping", "paying"], answer: 0 },
    { q: "You can ________ the internet here.", options: ["take", "use", "pay"], answer: 1 },
    { q: "Emily hates ________ in the mountains.", options: ["camping", "doing", "watching"], answer: 0 },
    { q: "You can ________ a coffee here.", options: ["have", "pay", "use"], answer: 0 },
    { q: "Alice likes ________ yoga.", options: ["doing", "going", "playing"], answer: 0 },
    { q: "Where can I ________ money in this town?", options: ["take", "have", "change"], answer: 2 },
    { q: "Enrique loves ________ out in restaurants.", options: ["eating", "going", "meeting"], answer: 0 },
    { q: "I'm sorry. You can't ________ your mobile phone here.", options: ["play", "take", "use"], answer: 2 },
    { q: "Do goes with ________.", options: ["to the gym", "photos", "yoga"], answer: 2 },
    { q: "Watch goes with ________.", options: ["films", "books", "music"], answer: 0 },
    { q: "Have goes with ________.", options: ["a shower", "a parking", "a work"], answer: 0 },
    { q: "Go goes with ________.", options: ["walking", "sleeping", "watching TV"], answer: 0 },
    { q: "Drive goes with ________.", options: ["work", "fast", "school"], answer: 1 },
    { q: "Use goes with ________.", options: ["money", "TV", "your mobile phone"], answer: 2 },
    { q: "Make goes with ________.", options: ["emails", "sport", "lunch"], answer: 2 },
    { q: "Buy goes with ________.", options: ["clothes", "the cinema", "sport"], answer: 0 },
    { q: "Play goes with ________.", options: ["the piano", "yoga", "friends"], answer: 0 },
    { q: "Take goes with ________.", options: ["photos", "an email", "the cinema"], answer: 0 },
  ],
  9: [

{q:"Vanya ________ a shower in the morning.",options:["always has","having always","is always having"],answer:0},{q:"What ________?",options:["are you watching","are you watch","you watching"],answer:0},{q:"Would you like to go out tonight? Yes, ________.",options:["I love","I love to","I'd love to"],answer:2},{q:"It ________ at the moment.",options:["rains","raining","isn't raining"],answer:2},{q:"Where is your brother ________ now?",options:["live","living","lives"],answer:1},{q:"Are you watching TV? No, I'm not. I ________.",options:["is working","work","am working"],answer:2},{q:"Maya ________ music in her bedroom.",options:["listens","listening to","is listening to"],answer:2},{q:"Are you ________ jeans? Yes, I am.",options:["wear","wears","wearing"],answer:2},{q:"________ for us?",options:["Is Antonio wait","Is Antonio waiting","Is waiting Antonio"],answer:1},{q:"________ anything important now?",options:["Do you do","Is you doing","Are you doing"],answer:2},{q:"________ in the evenings?",options:["Do you study","Do you studying","Does you study"],answer:0},{q:"Do you ________ Chinese?",options:["to speak","speaking","speak"],answer:2},{q:"Oh, no. It's ________. We can't drive to the airport.",options:["snow","snows","snowing"],answer:2},{q:"Carlos doesn't usually ________ coffee.",options:["drink","to drink","drinking"],answer:0},{q:"________ to go to the cinema with me?",options:["Are you like","Do you like","Would you like"],answer:2},{q:"I never ________ to bed late.",options:["go","going","to go"],answer:0},{q:"Where are you? I ________ the house now.",options:["leave","'m leaving","leaving"],answer:1},{q:"________ going to the concert with you?",options:["Are they","They are","Do they"],answer:0},{q:"We're ________ dinner at the moment.",options:["have","to have","having"],answer:2},{q:"What are you doing? I'm ________ my suitcase.",options:["'m pack","'m packing","packing"],answer:1},
    // --- Vocabulary: additional words and phrases ---
    { q: "Let's ________ at half past seven.", options: ["do", "have", "meet"], answer: 2 },
    { q: "Can I ________ a car, please?", options: ["arrive", "rent", "wait"], answer: 1 },
    { q: "There is always a lot of ________ in my city.", options: ["traffic", "bus stop", "travel"], answer: 0 },
    { q: "I always wear a ________ to work.", options: ["trousers", "shoes", "suit"], answer: 2 },
    { q: "We're ________ for our flight at the airport.", options: ["staying", "travelling", "waiting"], answer: 2 },
    { q: "Do you want to eat ________?", options: ["inside", "in", "outside"], answer: 2 },
    { q: "Amber is wearing a blue ________.", options: ["jacket", "jeans", "shoes"], answer: 0 },
    { q: "I'd like to ________ you something.", options: ["ask", "say", "speak"], answer: 0 },
    { q: "I want to buy some new ________.", options: ["dress", "jeans", "coat"], answer: 1 },
    { q: "Are you ________ in a hotel?", options: ["arriving", "leaving", "staying"], answer: 2 },
    { q: "Taxi goes with ________.", options: ["airport", "train", "car"], answer: 0 },
    { q: "Make goes with ________.", options: ["dinner", "homework", "traffic"], answer: 0 },
    { q: "Hotel goes with ________.", options: ["finish", "check in", "rent"], answer: 1 },
    { q: "Airport goes with ________.", options: ["bus stop", "a flight", "house"], answer: 1 },
    { q: "Book goes with ________.", options: ["a suitcase", "tickets", "home"], answer: 1 },
    { q: "Buy goes with ________.", options: ["presents", "home", "friends"], answer: 0 },
    { q: "Suit goes with ________.", options: ["car", "jeans", "tie"], answer: 2 },
    { q: "Waiter works in a ________.", options: ["hospital", "restaurant", "office"], answer: 1 },
    { q: "Pack goes with ________.", options: ["a taxi", "a suitcase", "skirt"], answer: 1 },
    { q: "A suit is a type of ________.", options: ["shirt", "jeans", "clothes"], answer: 2 },
  ],
  10: [

{q:"There ________ people at reception.",options:["aren't any","aren't some","isn't any"],answer:0},{q:"Petra ________ tired last night.",options:["wasn't","were","weren't"],answer:0},{q:"There are ________ chairs in the kitchen.",options:["any","some","a"],answer:1},{q:"Where ________ you last week?",options:["were","was","are"],answer:0},{q:"________ any shops near here.",options:["There aren't","There isn't","There are"],answer:0},{q:"________ a good view in that room.",options:["They is","There is","There are"],answer:1},{q:"Is there ________ park in this town?",options:["a","some","any"],answer:0},{q:"Were you in London last week? No, I ________.",options:["was","wasn't","weren't"],answer:1},{q:"I think there are ________ hotels in the town.",options:["not","some","any"],answer:1},{q:"________ any towels in the bathroom?",options:["Is there","Are there","There are"],answer:1},{q:"Was Rosa late for work this morning? Yes, ________.",options:["she late","was she","she was"],answer:2},{q:"Are there ________ good stories in that magazine?",options:["a","any","some"],answer:1},{q:"________ you yesterday?",options:["Where are","Where was","Where were"],answer:2},{q:"Is there a lift in the hotel? No, ________.",options:["it isn't","there isn't","there it isn't"],answer:1},{q:"Was ________ in the cinema yesterday afternoon?",options:["we","you","she"],answer:2},{q:"Where was your son's football match? It ________ the park.",options:["was in","were in","was there"],answer:0},{q:"There _______ swimming pool in the hotel.",options:["isn't a","isn't any","isn't some"],answer:0},{q:"There were ________ pictures on the walls.",options:["a","any","some"],answer:2},{q:"They ________ at home yesterday evening.",options:["wasn't","isn't","weren't"],answer:2},{q:"Is there a bank near here? No, ________.",options:["not there","there isn't","isn't there"],answer:1},
    // --- Vocabulary: additional words and phrases ---
    { q: "Which word is different from 'a shower'?", options: ["a toilet", "a garden", "a bath"], answer: 1 },
    { q: "Which word is different from 'a museum'?", options: ["a park", "a street", "a lift"], answer: 2 },
    { q: "Which word is different from 'a light'?", options: ["a lamp", "a towel", "a remote control"], answer: 1 },
    { q: "Which word is different from 'a supermarket'?", options: ["a spa", "a hospital", "a street"], answer: 2 },
    { q: "Which word is different from 'a restaurant'?", options: ["reception", "a gift shop", "a pillow"], answer: 2 },
    { q: "Which word is different from 'a cupboard'?", options: ["a table", "a chair", "the floor"], answer: 2 },
    { q: "You use this to go to the fifth floor.", options: ["a park", "a lamp", "a lift"], answer: 2 },
    { q: "You usually go here to do exercise.", options: ["a supermarket", "reception", "a gym"], answer: 2 },
    { q: "You can see this from the window in a good hotel.", options: ["a toilet", "a view", "a shop"], answer: 1 },
    { q: "You can stay here.", options: ["a bathroom", "a kitchen", "a hotel"], answer: 2 },
    { q: "You use this to turn on or turn off the TV.", options: ["a remote control", "a double bed", "wi-fi"], answer: 0 },
    { q: "There is a bath and a shower and some towels in this place.", options: ["a bedroom", "a gym", "a bathroom"], answer: 2 },
    { q: "It is on the bed; you can sleep on it.", options: ["a towel", "a lamp", "a pillow"], answer: 2 },
    { q: "There are waiters in this place. You can have dinner here.", options: ["a restaurant", "reception", "a spa"], answer: 0 },
    { q: "Yvonne isn't ________ home at the moment.", options: ["on", "in", "at"], answer: 2 },
    { q: "It's raining. Come ________ the umbrella.", options: ["on", "in", "under"], answer: 2 },
    { q: "Sam and Kevin are running ________ the park.", options: ["at", "in", "on"], answer: 1 },
    { q: "Robyn was ________ the bus this morning.", options: ["in", "at", "on"], answer: 2 },
    { q: "There are some keys ________ my bag.", options: ["at", "between", "in"], answer: 2 },
    { q: "My room is ________ the third floor.", options: ["in", "at", "on"], answer: 2 },
  ],
  11: [

{q:"Georgina ________ for three hours yesterday.",options:["study","studied","studies"],answer:1},{q:"What time ________ last night?",options:["does the train arrive","did the train arrive","did the train arrived"],answer:1},{q:"They ________ to have a coffee.",options:["did stop","stoped","stopped"],answer:2},{q:"Pavel ________ lunch at home yesterday.",options:["has","have","had"],answer:2},{q:"Where did Maggie go for lunch? She ________ to a small café.",options:["went","goed","did go"],answer:0},{q:"Laura ________ help her daughter with her homework yesterday.",options:["doesn't","didn't","not"],answer:1},{q:"What did you do in Europe? I ________ a lot of beautiful places.",options:["visited","visitd","visit"],answer:0},{q:"The children didn't ________ to sleep on the plane.",options:["go","goed","went"],answer:0},{q:"I ________ at the end of the film.",options:["cryed","cried","cryd"],answer:1},{q:"Did Anita ________ Turkish at university?",options:["study","studies","studied"],answer:0},{q:"What time ________?",options:["went they","did they go","did they went"],answer:1},{q:"My brother ________ a really nice meal for dinner last night.",options:["cooking","cooked","cooks"],answer:1},{q:"Last summer my brother ________ across the USA by train.",options:["travel","traveled","travelled"],answer:2},{q:"Did she get a bus to the train station? No, ________.",options:["she did","did she not","she didn't"],answer:2},{q:"________ in Madrid?",options:["Did they live","Did they lived","Lived they"],answer:0},{q:"We ________ the housework yesterday.",options:["did","went","got"],answer:0},{q:"Did you ________ the concert?",options:["like","likes","liked"],answer:0},{q:"Toni ________ an early flight this morning.",options:["did","get","got"],answer:2},{q:"Did you have breakfast? Yes, ________.",options:["I had","I did","I got"],answer:1},{q:"Alfonso ________ his mother last night.",options:["phone","phones","phoned"],answer:2},
    // --- Vocabulary: additional words and phrases ---
    { q: "I ________ a nice day at the spa yesterday.", options: ["had", "went", "did"], answer: 0 },
    { q: "Simon ________ to Brazil last year on holiday.", options: ["did", "went", "had"], answer: 1 },
    { q: "______ you watch TV last night?", options: ["Did", "Had", "Went"], answer: 0 },
    { q: "Marc didn't ________ up early yesterday.", options: ["got", "stay", "get"], answer: 2 },
    { q: "My sister ________ married on Saturday.", options: ["had", "did", "got"], answer: 2 },
    { q: "Davina didn't ________ out on Friday night.", options: ["get", "go", "went"], answer: 1 },
    { q: "This morning I ________ a coffee with my friends.", options: ["did", "had", "went"], answer: 1 },
    { q: "We ________ a taxi home last night.", options: ["had", "got", "went"], answer: 1 },
    { q: "The hotel is ________ the bank and the museum.", options: ["between", "near here", "next"], answer: 0 },
    { q: "Go ________ and the supermarket is on the right.", options: ["on", "right on", "straight on"], answer: 2 },
    { q: "______ left when you leave the train station.", options: ["Excuse me", "Go to", "Turn"], answer: 2 },
    { q: "There is a park ________ the hotel.", options: ["between", "opposite", "next"], answer: 1 },
    { q: "There's a very good Italian restaurant ________ of First Street and Queen Road.", options: ["opposite", "next to", "on the corner"], answer: 2 },
    { q: "_______. Is there a car park near here?", options: ["Excuse me", "Thanks", "Turn"], answer: 0 },
    { q: "Last night I ________ my flight to Berlin.", options: ["missed", "went", "had"], answer: 0 },
    { q: "Did you ________ your suitcase?", options: ["pack", "packed", "packing"], answer: 0 },
    { q: "They ________ in an expensive hotel.", options: ["stayed", "stay", "staying"], answer: 0 },
    { q: "We ________ a car when we were on holiday.", options: ["rented", "rent", "renting"], answer: 0 },
    { q: "She didn't ________ for us yesterday.", options: ["wait", "waited", "waiting"], answer: 0 },
    { q: "The opposite of left is ________.", options: ["right", "straight", "near"], answer: 0 },
  ],
  12: [

{q:"Sofia ________ anything at the shops.",options:["didn't bought","bought","didn't buy"],answer:2},{q:"How much ________ your trousers?",options:["were","was","is"],answer:0},{q:"Did Julia and Matteus leave the office at 6 o'clock? No, they ________.",options:["don't","didn't","left"],answer:1},{q:"The bus ________ on the corner of King's Street.",options:["stop","stoped","stopped"],answer:2},{q:"Michelle ________ me an email yesterday.",options:["didn't sent","didn't send","send"],answer:1},{q:"I ________ a really good time at the party last night.",options:["have","was have","had"],answer:2},{q:"When ________ you visit the new school?",options:["did","had","went"],answer:0},{q:"Alex ________ his friends he was sorry.",options:["asked","said","told"],answer:2},{q:"________ you late for work today?",options:["Is","Were","Was"],answer:1},{q:"Tania ________ some new jeans in the market.",options:["buy","buyed","bought"],answer:2},{q:"Did you ________ tennis on Wednesday?",options:["play","playd","played"],answer:0},{q:"Where ________?",options:["did stop the bus","did the bus stop","did stopped the bus"],answer:1},{q:"We ________ at a lovely hotel near the beach.",options:["stays","stayed","did stayed"],answer:1},{q:"What ________ last night?",options:["are you do","do you do","did you do"],answer:2},{q:"Rachel ________ to the train station to meet her friend.",options:["went","did go","did went"],answer:0},{q:"________ Hamed buy a new car yesterday?",options:["Was","Did","Can"],answer:1},{q:"My mother ________ two tickets for the concert.",options:["didn't booked","booked","not book"],answer:1},{q:"What time ________?",options:["did you arrive","you arrived","did you arrived"],answer:0},{q:"What ________ to the TV?",options:["happened","did happen","is happen"],answer:0},{q:"We ________ the food at that new restaurant last night.",options:["didn't liked","didn't like","like"],answer:1},
    // --- Vocabulary: additional words and phrases ---
    { q: "Which word is different from 'lunch'?", options: ["breakfast", "eat", "dinner"], answer: 1 },
    { q: "Which word is different from 'husband'?", options: ["son", "father", "sister"], answer: 2 },
    { q: "Which word is different from 'sweater'?", options: ["dress", "yellow", "T-shirt"], answer: 1 },
    { q: "Which word is different from 'concert'?", options: ["ticket", "flat", "box office"], answer: 1 },
    { q: "Which word is different from 'spa'?", options: ["pillow", "gym", "reception"], answer: 0 },
    { q: "Which word is different from 'lovely'?", options: ["awful", "nice", "good"], answer: 0 },
    { q: "Which word is different from 'taxi'?", options: ["airport", "train", "car"], answer: 1 },
    { q: "Which word is different from 'bank'?", options: ["supermarket", "shopping centre", "opposite"], answer: 2 },
    { q: "Which word is different from 'morning'?", options: ["afternoon", "September", "evening"], answer: 1 },
    { q: "Which word is different from 'fish'?", options: ["pasta", "coffee", "eggs"], answer: 1 },
    { q: "We ________ a good day.", options: ["did", "had", "were"], answer: 1 },
    { q: "Damian ________ for his girlfriend for an hour.", options: ["liked", "stopped", "waited"], answer: 2 },
    { q: "We ________ a really good film at the cinema.", options: ["sat", "saw", "went"], answer: 1 },
    { q: "______ you tired last night?", options: ["Did", "Had", "Were"], answer: 2 },
    { q: "Did you ________ me a message this morning?", options: ["say", "send", "see"], answer: 1 },
    { q: "They ________ to a new house last year.", options: ["left", "moved", "packed"], answer: 1 },
    { q: "I ________ really hungry this morning, so I had a big breakfast.", options: ["had", "was", "went"], answer: 1 },
    { q: "What did you ________ for dinner?", options: ["go", "have", "take"], answer: 1 },
    { q: "Patrick ________ an important email last night.", options: ["did", "told", "wrote"], answer: 2 },
    { q: "We ________ goodbye and exchanged email addresses.", options: ["sent", "told", "said"], answer: 2 },
  ]
};
